# Generated by Django 3.0.8 on 2020-10-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalBanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Банк')),
                ('first', models.IntegerField(verbose_name='Стоимость внедрения')),
                ('second', models.FloatField(verbose_name='Стоимость обслуживания (руб./мес.)')),
                ('third', models.FloatField(verbose_name='Комиссия на перевод (%)')),
                ('fourth', models.FloatField(verbose_name='Online-bank')),
                ('fifth', models.BooleanField(verbose_name='Мобильное приложение')),
                ('sixth', models.BooleanField(verbose_name='SMS-информирование')),
                ('seventh', models.BooleanField(verbose_name='Ведение переписки с банком')),
                ('eighth', models.BooleanField(verbose_name='Круглосуточная поддержка')),
                ('nineth', models.BooleanField(verbose_name='Конвертация валюты')),
                ('tenth', models.BooleanField(verbose_name='Интеграция с 1С')),
                ('eleventh', models.BooleanField(verbose_name='Получение информации о расчетном счете')),
                ('twelveth', models.BooleanField(verbose_name='Платежи и переводы валютой')),
                ('thirteenth', models.BooleanField(verbose_name='Продажа валюты')),
            ],
            options={
                'verbose_name': 'Банк для юридических лиц',
                'verbose_name_plural': 'Банки для юридических лиц',
            },
        ),
    ]
