# Generated by Django 3.0.8 on 2020-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_legalbanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalbanks',
            name='fourth',
            field=models.BooleanField(verbose_name='Online-bank'),
        ),
        migrations.AlterField(
            model_name='legalbanks',
            name='second',
            field=models.IntegerField(verbose_name='Стоимость обслуживания (руб./мес.)'),
        ),
    ]
